name: teeth_anatomy
description: teeth_anatomy shows the anatomy of the tooth and is a good package for use in medical software

repository: "https://github.com/mohammadprgrm20123/Teeth_anatomy"

version: 0.0.1

environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  touchable: ^1.0.2
  flutter_svg: ^1.1.6



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: 3.0.0

flutter:


  uses-material-design: true

  assets:
     - lib/ss.svg

